name: Panther Thrift Shop Web Application Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: panther-thrift-shop

      - name: Build Project
        run: npm run build
        working-directory: panther-thrift-shop

      - name: Disable Jekyll
        run: touch outputdir/.nojekyll

      - name: Copy Build Output
        run: |
          mkdir -p outputdir
          mv panther-thrift-shop/dist/* outputdir/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: outputdir

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
