name: PTS Web Application Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd panther-thrift-shop
          run: npm install

      - name: Build
        run: npm run build

      - name: Copy Over the App
        run: |
          mkdir -p outputdir
          mv dist outputdir/app

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Docs
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs
          destination: outputdir/docs
          
      - name: Upload Static Files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with: 
          path: outputdir

      - name: Pages Folder
        uses: actions/upload-artifact@v4
        with:
          name: pages-files
          path: outputdir
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
