name: Sync with Hanover-CS Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: Hanover-CS/HC25-Jayson-Baya-Senior-Project
          token: ${{ secrets.GITHUB_TOKEN }}
          path: source_repo

      - name: Push to Forked Repository
        run: |
          cd source_repo
          git remote set-url origin https://github.com/bayaj0110/HC25-Jayson-Baya-Senior-Project.git
          git push origin main
