name: Sync with Hanover-CS Repo

on:
  push:
    branches:
      - main 
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v4
        with:
          repository: bayaj0110/HC25-Jayson-Baya-Senior-Project
          token: ${{ secrets.HANOVER_CS_TOKEN }}

      - name: Hanover-CS/HC25-Jayson-Baya-Senior-Project repository
        run: git remote add upstream https://github.com/Hanover-CS/HC25-Jayson-Baya-Senior-Project

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push Changes to Forked Repository
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.HANOVER_CS_TOKEN }}
