name: Sync Fork to bayaj0110 repo

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4 # Updated to v4 for Node 20 support
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "Jayson Baya"
          git config user.email "yesjaysonb@gmail.com"

      - name: Add Forked Remote
        run: git remote add fork https://bayaj0110:${{ secrets.HANOVER_CS_TOKEN }}@github.com/bayaj0110/HC25-Jayson-Baya-Senior-Project.git

      - name: Push Changes to Fork
        run: |
          git push fork main --force
