name: Sync Fork to bayaj0110/HC25-Jayson-Baya-Senior-Project

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4 # Updated to v4 for Node 20 support
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set Up Authentication
        run: |
          git remote set-url origin https://bayaj0110:${{ secrets.HANOVER_CS_TOKEN }}@github.com/bayaj0110/HC25-Jayson-Baya-Senior-Project.git
          git config user.name "Jayson Baya"
          git config user.email "yesjaysonb@gmail.com"

      - name: Fetch Upstream Changes
        run: git fetch origin

      - name: Push Changes to Fork
        run: |
          git push origin main --force
