name: Sync with Hanover-CS Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "yesjaysonb@gmail.com"
          git config --global user.name "bayaj0110"

      - name: Clone and sync with destination repository
        run: |
          # Clone the forked repository (destination) where you want to sync
          git clone https://${{ secrets.HANOVER-CS-TOKEN }}@github.com/bayaj0110/HC25-Jayson-Baya-Senior-Project.git
          cd HC25-Jayson-Baya-Senior-Project

          # Add the original repository (source) as a remote and fetch updates
          git remote add upstream https://${{ secrets.HANOVER-CS-TOKEN }}@github.com/Hanover-CS/HC25-Jayson-Baya-Senior-Project.git
          git fetch upstream main

          # Merge changes from the source repo's main branch
          git merge upstream/main

          # Push the changes to the fork's main branch
          git push origin main
        env:
          HANOVER-CS-TOKEN: ${{ secrets.HANOVER-CS-TOKEN }} 
